# .readthedocs.yml

version: 2

build:
  image: latest

python:
  version: 3.7
  install:
    - method: pip
      path: .

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

conda:
  environment: docs/doc_env.yaml
